# Deployment with liveness and readiness
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teacher-app
  template:
    metadata:     
      name: teacher-pod
      labels:
        app: teacher-app
    spec:
      containers:
      - name: teacher
        image: kritikasingh02/teacher:v3
        ports: 
        - containerPort: 8084
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 5
          periodSeconds: 5
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: teacher-service
spec:
  type: LoadBalancer
  selector: 
    app: teacher-app
  ports: 
    - port: 1234
      targetPort: 8084